### PR TITLE
readme and code for problem 4

### PR DESCRIPTION
**Pull request by tgreenhalgh**

### CODE REVIEW

**Review by ameykhale — CHANGES_REQUESTED** [review]
Code doesn't execute within time limits. Please check [here](https://www.hackerrank.com/contests/projecteuler/challenges/euler004/problem)

**Comment by tgreenhalgh** [comment]
ah, OK, the problem in Project Euler is different from the problem in Hackerrank. Will change the code to match what Hackerrank is asking for.

**Comment by tgreenhalgh** [comment]
now passes all Hackerrank tests

**Comment by tgreenhalgh** [comment]
just FYI, 1000 runs of this version looking for under 800000  took 3.701987721s and
1000 runs of https://github.com/funoctis/Project-Euler-Go/pull/6 took 7.109400646s

Both pass Hackerrank, so not really that important :)

**Pull request merged**
