### PR TITLE
Added code and documentation for problem 011 and 013

### PR DESCRIPTION
**Pull request by amalshaji**

### CODE REVIEW

**Review by ameykhale — APPROVED** [review]
You're on a roll

**Comment by amalshaji** [comment]
> You're on a roll

Should we add custom test suites?? like 009_test.go

**Comment by ameykhale** [comment]
You can if you want to, but make the input numbers large to check how optimised the solution really is. And time it

**Comment by amalshaji** [comment]
Thinking about it

**Comment by amalshaji** [comment]
Is there any way I could get the test cases from hackerrank?

**Pull request merged**
